### ISSUE TITLE
Broken after last update?

### ISSUE THREAD

**Issue by htilly** [Menturan/MMM-Namnsdag#1]
Hi!

It seems to be broken after last update. 
Now it simply says:
"Hämtar dagens namn.."
And then nothing...

**Comment by Menturan** [comment]
Hi @htilly!
Thanks for pointing this out! :)
I thought it was just my MagicMirror that failed to load the module. But it was a bug. A really silly bug also. :P
Thanks again!

**Comment by htilly** [comment]
Thanks for a quick fix, and thanks for a simple, yet useful, module!

ps. if you have some time over...  what do you think of this function for a module?:
https://forum.magicmirror.builders/topic/9684/opening-hours-for-stores-places-thru-google-api
ds.  :-D

**Comment by Menturan** [comment]
Sounds like a great idea! Should be pretty easy to write to. 
I will think about it. :)

**Comment by htilly** [comment]
Exactly the answer i was looking for!!
:-D
