### ISSUE TITLE
MagicMirror 2.25 breaks module - easy fix

### ISSUE THREAD

**Issue by mickecamino** [Menturan/MMM-Namnsdag#8]
Yesterday MagicMirror was upgraded to 2.25, and during the upgrade node-fetch is removed as per the documentation:
`Replace node-fetch with internal fetch (#2649) and remove digest-fetch`

The easiest fix os to remove the line:
`const fetch = require("node-fetch");`
from node_helper.js. However, this will break older MM installs

**Comment by Menturan** [comment]
This module uses its own node-fetch and isn't dependent on Magicmirrors dependency's. 
Please run `yarn install` in the module folder and it should start working.

**Comment by mickecamino** [comment]
And when the next MagicMirror update comes along and remove node-fetch, it will crash again.

**Comment by Menturan** [comment]
No, it wont. I just tested with the latest version of MagicMirror with both NodeJs 16 and 18 and it works fine. As I said it uses its own node-fetch. Please follow the install instructions in README.
